# Whether to show verbose messages, such as when downloading dependencies or when protobuf descriptors are skipped.
#
# Example:
# verbose_mode: false

# List of checks that should be excluded from analysis.
# enum_value_has_comments # checks if an enum value has leading comments.
# field_description_ends_with_dot_or_question_mark # checks if a field's description ends with a dot or a question mark.
# field_description_starts_with_capital # checks if a field's description starts with a capital letter.
# field_has_correct_json_name # checks if a field's JSON name tag is correct.
# field_has_no_description # checks if a field has no description.
# field_name_is_snake_case # checks if a field's name is in snake_case.
# method_has_body_tag # checks if methods with a required body have the correct body tag.
# method_has_correct_input_name # checks if the method input is named correctly.
# method_has_default_error_response # checks if a default error response is defined in the method.
# method_has_http_path # checks if an HTTP path is specified for the method.
# method_has_swagger_description # checks if a method has a valid Swagger description.
# method_has_swagger_summary # checks if a method has a valid Swagger summary.
# method_has_swagger_tags # checks if a method has appropriate Swagger tags.
# method_has_version # checks whether a method specifies a version.
#
# Example:
# excluded_checks:
#   - enum_value_has_comments
#   - field_description_ends_with_dot_or_question_mark
#   - field_description_starts_with_capital
#   - field_has_correct_json_name
#   - field_has_no_description
#   - field_name_is_snake_case
#   - method_has_body_tag
#   - method_has_correct_input_name
#   - method_has_default_error_response
#   - method_has_http_path
#   - method_has_swagger_description
#   - method_has_swagger_summary
#   - method_has_swagger_tags
#   - method_has_version

# List of full protopaths that should be excluded from analysis.
#
# Example:
# excluded_descriptors:
#   - package.Message.NestedMessage.Field
