package cmd

import (
	"fmt"

	"github.com/oshokin/protolinter/internal/checker"
	"github.com/oshokin/protolinter/internal/config"
	"github.com/spf13/cobra"
)

// checkCmd represents the check command.
var checkCmd = &cobra.Command{
	Use:   "check [files...]",
	Short: "Check protobuf files for compliance with coding conventions",
	Long: `The 'check' command analyzes the provided protobuf files to ensure they
comply with coding conventions and standards. It verifies that the files are
properly formatted and follow recommended practices.`,
	Example: "protolinter check --config=config.yaml file.proto       # Analyze a specific protobuf file",
	Args:    cobra.MinimumNArgs(1),
	Run: func(cmd *cobra.Command, files []string) {
		configPath, _ := cmd.Flags().GetString("config")
		isMimirFile, _ := cmd.Flags().GetBool("mimir")

		checker.ExecuteCheck(files, configPath, isMimirFile)
	},
}

func init() { //nolint: gochecknoinits // Code is generated by cobra-cli.
	checkCmd.Flags().StringP("config", "c", "",
		fmt.Sprintf("path to the custom configuration file (default is '%s')",
			config.DefaultConfigName))
	checkCmd.Flags().BoolP("mimir", "m", false,
		"path to the mimir file containing a list of paths containing protobuf files, "+
			"if this flag is set, the first file specified as an argument is expected to be the mimir file")

	rootCmd.AddCommand(checkCmd)
}
