package cmd

import (
	"github.com/oshokin/protolinter/internal/checker"
	"github.com/spf13/cobra"
)

// listCmd represents the list command.
var listCmd = &cobra.Command{
	Use:   "list [files...]",
	Short: "Generate a list of full protobuf element names",
	Long: `The 'list' command generates a list of full names for each protobuf element
found in the provided files.`,
	Example: "protolinter list file.proto       # Generate a list of full protobuf element names",
	Args:    cobra.MinimumNArgs(1),
	Run: func(_ *cobra.Command, files []string) {
		checker.ExecuteListProtoFullNames(files)
	},
}

func init() { //nolint: gochecknoinits // Code is generated by cobra-cli.
	rootCmd.AddCommand(listCmd)
}
